Feature/prog 35 Добавление бэкенда авторизации (логин & регистрация)
iOS-vk-education/2022_1s_PROGulky pull request #19
Opened 2022-12-14 10:01 UTC by K1selev

2022-12-14 10:47 UTC, puzzzik requested changes

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Coordinators/CoordinatorProtocol.swift
> +    @objc optional func finish()
Мы вчера выяснили, что objc optional нам не понадобилось

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Coordinators/AppCoordinator.swift
> +    var rootNavigationController: UINavigationController
а зачем тут navigationController?

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Coordinators/AppCoordinator.swift
> +        rootNavigationController = UINavigationController()
ну и здесь тоже

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Coordinators/CoordinatorProtocol.swift
> +    @objc optional func finish()
так что оставь просто протокол с одним методом - start()

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Coordinators/ProfileCoordinator.swift
> +//        rootNavigationController.setViewControllers([profileViewController], animated: false)
коммент нужно убрать

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Coordinators/ProfileCoordinator.swift
> +    func loginModuleWantsToOpenSingUp() {
loginModuleWantsToOpenRegistrationModule

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Login/Interactor/LoginInteractor.swift
> +    let urlAdress = "http://37.140.195.167:5000"
private

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Login/Interactor/LoginInteractor.swift
> +    func login(email: String, password: String) -> (User?) {
лучше все, что связано с URLSession перенести в твой APIManager
А в этом методе просто дергать сам менеджер
Можешь посмотреть, как это у Семена сделано

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Login/Interactor/Services/ApiManagerLogin.swift
> +    case login
а вот это лучше добавить в готовый ApiType, который делал Семен
Просто добавь туда свой case

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Login/Interactor/Services/ApiManagerLogin.swift
> +final class ApiManagerLogin {
И получается, свой менеджер для логина вообще не нужен
Давай все перенесем в один менеджер - Семена

И тот менеджер в отдельную папку Services в корне проекта

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Login/Presenter/LoginModuleIO.swift
> +    func loginModuleWantsToOpenSingUp()
loginModuleWantsToOpenRegistration

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Login/View/LoginViewController.swift
> +                                               role: login?.role.description ?? "")
Может, здесь создать User'а и в метод передавать его, а не все поля по отдельности

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Login/Presenter/LoginPresenter.swift
> +    weak var moduleOutput: LoginModuleOutput?
private

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Models/UserDefaultsKeys.swift
> +    let role = "role"
Сделай тут все поля static, тогда тебе не придется создавать структуру всегда
А просто обращаться UserKeys.token

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Models/UserDefaultsKeys.swift
> +    let role = "role"
Либо же можно сделать enum

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Registration/Interactor/RegistrationInteractor.swift
> +    let urlAdress = "http://37.140.195.167:5000"
private

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Registration/Interactor/RegistrationInteractor.swift
> +    func registration(email: String, name: String, password: String) -> (User?) {
Тут все то же самое
В этом методе ты будешь дергать метод ApiManager'а и проверять ответ через completion

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Registration/Presenter/RegistrationPresenter.swift
> +    weak var moduleOutput: RegistrationModuleOutput?
private

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Registration/Presenter/RegistrationPresenter.swift
> +    func didSelectSignUpBtn(token: String, id: Int, email: String, name: String, role: String) {
Здесь тоже можно не передавать все поля, а передать заполненную структуру User

Что если у нас к User в будущем появятся новые поля? Добавлять еще один параметр?

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Registration/View/RegistrationViewController.swift
> +//            view.frame.origin.y -= keyboardHeight
комментарий

2022-12-14 10:47 UTC, puzzzik commented on PROGulky/Modules/Registration/View/RegistrationViewIO.swift
> +    func didSelectSignUpBtn(token: String, id: Int, email: String, name: String, role: String)
Вот здесь поменять все параметры на User

2022-12-14 11:38 UTC, puzzzik commented on PROGulky/Modules/Login/Interactor/Services/ApiManagerLogin.swift
> +final class ApiManagerLogin {
пока в отдельную папку не переноси, конфликты будут
Я в своем пре потом сделаю

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Coordinators/ProfileCoordinator.swift
> +        let isLoggedOut = UserDefaults.standard.bool(forKey: "isLoggedOut")
Общаться с UserDefaults лучше через прослойку. Manager или хотя бы interactor. Не крит

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Coordinators/ProfileCoordinator.swift
> +        let profileViewController = builder.build(self)
если isLoggedOut = true, тебе разве нужно создавать profileViewController?

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Coordinators/ProfileCoordinator.swift
> +        let profileView = builder.build(self)
здесь не нужен rootNavigationController.dismiss(animated: false) ?

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Login/Interactor/LoginInteractor.swift
> +    let urlAdress = "http://37.140.195.167:5000"
http://37.140.195.167 надо вынести в константы. Уже 3 раза повторяется. Если изменится, везде менять

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Login/Interactor/LoginInteractor.swift
> +        let semaphore = DispatchSemaphore(value: 0)
Круто что заиспользовал. Но для этого обычно используют убегающие замыкания.

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Login/Interactor/LoginInteractor.swift
> +    func login(email: String, password: String) -> (User?) {
Лучше возвращать и ошибку тоже

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Login/Interactor/Services/ApiManagerLogin.swift
> +    func getExcursions(completion: @escaping (Result<User, Error>) -> Void) {
Лайк

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Login/Interactor/Services/ApiManagerLogin.swift
> +                // completion(.success(excursions))
коммент

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Login/Presenter/LoginPresenter.swift
> +        let defaults = UserDefaults.standard
Лучше через прослойку. Писал выше

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Login/View/LoginViewController.swift
> +        if emailField.text == "" {
большая вложенность. используй guard

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Profile/View/ProfileUserInfoHeader.swift
> +        label.text = TextConstantsProfile.titleUserStatus + " - " + (UserDefaults.standard.string(forKey: UserKeys().role) ?? "")
UserDefaults в viewController это прям такое себе. Презентер должен передавать эти данные

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Registration/View/RegistrationViewController.swift
> +        if emailField.text == "" {
тоже вложенность

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Registration/View/RegistrationViewController.swift
>      @objc func didTapRestoreButton() {
private

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Registration/View/RegistrationViewController.swift
>      @objc func keyboardWillShow(notification: NSNotification) {
private

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Registration/View/RegistrationViewController.swift
>      @objc func didTapButtonSignUp() {
private

2022-12-14 13:31 UTC, OlegGibadulin commented on PROGulky/Modules/Registration/View/RegistrationViewController.swift
>      func textFieldShouldReturn(_ textField: UITextField) -> Bool {
возможно тоже private. пройдись по файлику

2022-12-14 13:59 UTC, puzzzik commented on PROGulky/Coordinators/ProfileCoordinator.swift
> +        let profileView = builder.build(self)
А зачем?
Мы тестили вчера, там логика показа и закрытия четенько работает

2022-12-21 09:35 UTC, OlegGibadulin commented on PROGulky/Modules/Login/View/LoginViewController.swift
> +        guard passwordField.text != "" else {
можешь объединить это в один guard, чтобы не было дублирования кода. не крит

2022-12-21 09:35 UTC, OlegGibadulin commented on PROGulky/Modules/Login/View/LoginViewController.swift
> +        token = login?.token
почему бы не присвоить значения сразу на 117 стррочке?

2022-12-21 09:35 UTC, OlegGibadulin commented on PROGulky/Modules/Login/View/LoginViewController.swift
> +        passwordField.layer.borderColor = UIColor.lightGray.cgColor
лучше вынести это в отдельный метод и передавать туда нужный textField

2022-12-21 09:35 UTC, OlegGibadulin commented on PROGulky/Modules/Login/View/LoginViewController.swift
> +        passwordField.layer.borderColor = UIColor.lightGray.cgColor
чтобы не было дублирования

2022-12-21 09:35 UTC, OlegGibadulin commented on PROGulky/Modules/Login/View/LoginViewController.swift
> +        if token == nil {
такие проверки с return лучше делать через guard, тогда избавишься от дальнейшей вложенности

2022-12-21 09:35 UTC, OlegGibadulin commented on PROGulky/Modules/Registration/View/RegistrationViewController.swift
> +    @objc private func didTapButtonSignUp() {
все те же самые замечания что и выше

2022-12-21 09:39 UTC, OlegGibadulin commented
В плане дублирования кода почитай про паттерн DRY

2022-12-22 19:03 UTC, K1selev commented on PROGulky/Modules/Login/View/LoginViewController.swift
> +        passwordField.layer.borderColor = UIColor.lightGray.cgColor
Доделаю

2022-12-22 19:03 UTC, K1selev commented on PROGulky/Modules/Login/View/LoginViewController.swift
> +        passwordField.layer.borderColor = UIColor.lightGray.cgColor
В другой задаче

2022-12-22 22:21 UTC, OlegGibadulin approved these changes

2022-12-22 22:21 UTC, OlegGibadulin commented on PROGulky/Modules/Registration/View/RegistrationViewController.swift
> +            static var bottomOffset: CGFloat = -60
var в константах это интересно

2022-12-22 22:21 UTC, OlegGibadulin commented on PROGulky/Services/UserDefaultsLoginService.swift
> +        isLogin = true // подумать как по другому
да норм

2022-12-22 22:22 UTC, OlegGibadulin approved these changes

2022-12-22 22:23 UTC, merged