Верстка списка экскурсий
iOS-vk-education/2022_1s_PROGulky pull request #7
Opened 2022-11-10 23:23 UTC by spyatachkov

Сверстал список экскурсий (пока еще на якорях, а не на SnapKit)
![Simulator Screen Shot - iPhone 11 Pro Max - 2022-11-11 at 01 56 29](https://user-images.githubusercontent.com/69919800/201226751-3a981d7f-4a81-4706-a5e1-b7e1804278b4.png)

2022-11-11 01:57 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/View/ExcursionsCell.swift
> +class ExcursionCell: UITableViewCell {
final

2022-11-11 01:57 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/Presenter/ExcursionsListDisplayDataFactory.swift
> +final class ExcursionsListDisplayDataFactory: ExcursionsListDisplayDataFactoryProtocol {
за фабрику лайк. а вот за структуру Excursion нет. Excursion это должна быть твоя модель, которая придет с бека. Здесь тебе надо из нее создавать вью модельку. Аля ExcursionListCellViewModel. И уже с этой вью модельной работать. сделать из них массив, прокидывать в ячейку и тд.

2022-11-11 01:57 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/Presenter/ExcursionsListDisplayDataFactory.swift
> +final class ExcursionsListDisplayDataFactory: ExcursionsListDisplayDataFactoryProtocol {
Плюс хранить UIImage в модели зло, потому что UIImage это твой ui, а это уровень view (VIPER). Храни инфу о картинке. Это либо название либо урл. В твоем случае с бека будет приходить урл. Храни его здесь. А вот UIImage надо создавать в самой ячейке

2022-11-11 01:57 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/Presenter/ExcursionsListDisplayDataFactory.swift
> +final class ExcursionsListDisplayDataFactory: ExcursionsListDisplayDataFactoryProtocol {
Плюс force unwrap это зло

2022-11-11 01:57 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListViewController.swift
> +    var excursions: [Excursion] = []
Массив excursions должен хранится на уровне презентера. Потому что вся бизнес логика, которая будет завязана на этом массиве, тоже должна быть в презентере.

2022-11-11 01:57 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListViewController.swift
> +    var excursions: [Excursion] = []
К примеру если бы нужно было делать пагинацию, то работа с ней была бы в презентере

2022-11-11 01:57 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListViewController.swift
> +        let data = output.getExcursionsListDisplayData()
назови метод didLoadView и в презенетере делай все необходимые вещи на загрузку страницы. В данном случае загрузку экскурсий

2022-11-11 01:57 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListViewController.swift
> +        let data = output.getExcursionsListDisplayData()
И вызывай метод уже после setupUI()

2022-11-11 01:57 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListViewController.swift
> +        excursions.count
excursions в presenter будет private. Здесь должен быть вызов метода output.itemsCount

2022-11-11 01:57 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListViewController.swift
> +        let excursion = excursions[indexPath.row]
здесь output.item(for: indexPath)

2022-11-11 01:57 UTC, OlegGibadulin commented
Эти моменты поправить и можно лить

2022-11-11 06:13 UTC, puzzzik requested changes

2022-11-11 06:13 UTC, puzzzik commented on PROGulky/Modules/ExcursionsList/View/Constants.swift
> +struct Constants {
Назови структуру ExcursionsListConstants
Она же будет доступна во всем проекте, и таких констант будет много

2022-11-11 06:13 UTC, puzzzik commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListViewController.swift
> +        let data = output.getExcursionsListDisplayData()
То есть этот метод тебе не будет возвращать массив экскурсий, он не нужен в контроллере

2022-11-11 06:13 UTC, puzzzik commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListViewController.swift
> +        let excursion = excursions[indexPath.row]
И метод output.item(for: indexPath) тебе будет возвращать как раз экземпляр твоей структуры с дисплей датой
Как предложил Олег ExsursuionListViewModel


А в самом методе item(for: indexPath) ты будешь обращаться к фабрике: передавать туда экземпляр модельки, которая придет с бека, как раз Excursion, а возвращать он будет экземпляр ExsursuionListViewModel в котором будут расставлены поля

Это нужно, если нам для ячейки нужны будут немного другие поля модельки, которая приходит с бека

2022-11-11 08:09 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListViewController.swift
> +        let data = output.getExcursionsListDisplayData()
Да вместо этого метода пропиши здесь метод output.didLoadView

2022-11-11 09:18 UTC, puzzzik commented on PROGulky/Modules/ExcursionsList/View/Extensions/UIView+Extensions.swift
> +extension UIView {
Вынести экстеншены в отдельную папку в корне проекта

2022-11-12 02:32 UTC, OlegGibadulin commented
История про модельку. У тебя будет 2 модели. Доменная модель и вью модель.

**Доменная модель** - это codable модель, которая хранит данные с бека. Интерактор возвращает именно её. И её ты передаешь в фабрику. Из данных этой модели ты формируешь **вью модель**.

**Вью модель** - это модель, которая хранит данные которые непосредственно ты будешь отображать на экране. 

К примеру, у тебя есть **excursionParametersLabel**, который отображает строку с параметрами. **Доменная модель** будет хранить 3 отдельных поля: часы, км и точки. А вот **вью модель** будет хранить уже готовую строчку, которую ты просто будешь вставлять в label.

Весь флоу выглядит так:
**Вью конроллер** -> говоришь презентеру, что он вью конроллер загрузил вьюху и готов отображать данные (вызов output.didLoadView)
**Презентер** -> запрашиваешь экскурсии у интерактора
**Интерактор** -> запрашиваешь данные с бека, кладешь их в доменную модель Excursion, передаешь массив Excursion презентеру
**Презентер** -> проходишься по этому массиву и передаешь каждую модельку фабрике
**Фабрика** -> получает доменную модель Excursion, создает на ее основе вью модель ExsursuionListViewModel
**Презентер** -> сохраняет полученный массив вью моделек ExsursuionListViewModel у себя в переменной excursions и говоришь вью конроллереру обновится
**Вью конроллер** -> на основе массива вью моделек ExsursuionListViewModel строит свои ячейки

2022-11-12 03:14 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListConstants.swift
> +    enum ExcursionsListScreen {
Повторения слова Excursions лучше убрать. Раз у тебя основная структура уже имеет слово Excursions. Для вложенных можно убрать Excursions, тк и так понятно что это относится к ExcursionsListConstants

2022-11-12 21:37 UTC, puzzzik commented on PROGulky/Modules/ExcursionsList/Presenter/ExcursionsListDisplayDataFactory.swift
> +    func setExcursionsListDisplayData() -> [Excursion]
Этот метод здесь не нужен
Но если хочешь пока оставить какую-то информацию в ячейке, то пометь комментарием, что метода там не должно быть

2022-11-12 21:37 UTC, puzzzik commented on PROGulky/Modules/ExcursionsList/View/Excursion.swift
> +//  Excursion.swift
Назови файлик ExcursionViewModel

2022-11-12 21:37 UTC, puzzzik commented on PROGulky/Modules/ExcursionsList/View/Excursion.swift
> +}
Перенеси в отдельную папку Models в корне проекта в файлик Excursion

2022-11-13 08:17 UTC, OlegGibadulin approved these changes

2022-11-13 08:17 UTC, OlegGibadulin commented on PROGulky/Modules/ExcursionsList/View/ExcursionsListViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: ExcursionsListConstants.ExcursionCell.reuseId) as! ExcursionCell // swiftlint:disable:this force_cast
чтобы избежать Force unwrap используй guard
```
guard let cell = tableView.dequeueReusableCell(withIdentifier: ExcursionsListConstants.ExcursionCell.reuseId) as? ExcursionCell else {
return UITableViewCell()
}
```

2022-11-13 19:51 UTC, puzzzik approved these changes

2022-11-14 03:27 UTC, merged